# -*- python -*-

# SConscript to build the tests

env = Environment()
tests = []

env["LIBPATH"] = "#/"
env["CPPPATH"] = "#/include"

env["CPPDEFINES"] = [env["PLATFORM"].upper()]

if env["PLATFORM"] == "win32":
    env["CCFLAGS"].append("/EHsc")
    env["CCFLAGS"].append("/W3")

elif env["PLATFORM"] == "posix":
    env["CCFLAGS"].append("-g")

# # Exception
tests.append(env.Program(target="exception_test",
                         source="exception_test.cpp",
                         LIBS="uaapi"))

# Logger
tests.append(env.Program(target="logger_test",
                         source="logger_test.cpp",
                         LIBS="uaapi"))

# # Singleton
tests.append(env.Program(target="singleton_test",
                         source="singleton_test.cpp",
                         LIBS="uaapi"))

Return("tests")
